### PR TITLE
Merge master <- ics_event_end_date Fixes nil end_date for ics activities. Fixes #453

### LINKED ISSUE #453: Event end date should be before begin date

### PR DESCRIPTION
**Pull request by koenjdejong**
The end_time of any activity on our site does not have to be defined. We want to keep it that way, but ical events require an enddate for an event once a begindate is set. 
Therefore, if an endtime is **not** defined, we declare it as original time with an additional hour, as many standard calendars do. 
Another fix is that it was possible to for the endtime to be before the begintime. This issue has now been resolved.

### CODE REVIEW

**Review by dexbleeker — APPROVED** [review]

File: app/models/event.rb [hunk 1]
```diff
@@ -21,7 +22,12 @@ def to_ics
     url = "https://zondersikkel.nl/events/#{self.id}"
     event = Icalendar::Event.new
     event.dtstart = date.strftime('%Y%m%dT%H%M%S')
-    event.dtend = end_time.strftime('%Y%m%dT%H%M%S')
+    if end_time.nil?
+      # standard endtime is + one hour for activities, since an endtime has to be defined within an ics activity and not on our site
+      event.dtend = (date + 1.hour).strftime('%Y%m%dT%H%M%S')
+    else
+      event.dtend = end_time.strftime('%Y%m%dT%H%M%S')
+    end
```
Comment (jackozi) [inline app/models/event.rb:30]: event.dtend = if end_time.blank? 
    event.dtend = (date + 1.hour).strftime('%Y%m%dT%H%M%S')
  else
    end_time.strftime('%Y%m%dT%H%M%S')
end

File: app/models/event.rb [hunk 2]
```diff
@@ -67,4 +73,11 @@ def attendee_count
   def to_s
     title
   end
+
+  private
+
+  def begin_before_end_time
+    return unless date && end_time
+    errors.add(:end_time, 'De activiteit eindigt voordat hij begint.') if date > end_time
```
Comment (jackozi) [inline app/models/event.rb:81]:
```
  if date.before? end_time
```
